### ISSUE TITLE
Add trigger function to alrmaserver

### ISSUE THREAD

**Issue by pixiandreas** [juggie/AlarmServer#23]
Hello i am start to use my sensors to trigger actions in my home.
It would be perfect if it possible to add a trigger function to alarmserver

example:
When  Zone 1 goes to open execute a script/http request/mail/ and more

**Comment by pbxip** [comment]
Yes it will be great to have triggers

**Comment by juggie** [comment]
Old ticket, but as part of rewrite in tornado branch, I am about to add a plugin system which will provide triggers.  Stand by.

**Comment by juggie** [comment]
Basic event system added.  Plugin system to follow.

**Comment by juggie** [comment]
Done, you can hang off 3 kinds of events.  'zone', 'partition', 'statechange'.

**Comment by juggie** [comment]
Filtering added to event system.  You can filter out zones/partitions you wish to ignore when you register an event to listen to.  In order to do what you want, you'll need to add plugins into plugin folder.  See pushover plugin for an example.  Additional plugins are welcome.

**Comment by adrianmihalko** [comment]
Can you be more generic, how do I setup a notification for statechange? I have enabled Pushover, but I am not receiving any notification.

**Comment by juggie** [comment]
Do you have any message in the logs when the stage change happens?

**Comment by juggie** [comment]
@adrianmihalko  I just tested it btw, works perfect w/ push over.  This is an old issue.  If you have a issue with push over, please open a new ticket.  Make sure your push over ID is set properly in the config.
