### ISSUE TITLE
Disconnected after login sequence

### ISSUE THREAD

**Issue by ekw** [juggie/AlarmServer#30]
I always get disconnected after the login sequence.  Any idea why?  I am able to telnet into my Envisalink and send/receive commands fine.  I'm running AlarmServer on Python 2.7.3 on Debian Linux kernel 3.8.13 on a beaglebone black.

Mar 31 21:52:00 alarmserver INFO: Using configuration file alarmserver.cfg
Mar 31 21:52:00 alarmserver INFO: ------------------------------
Mar 31 21:52:00 alarmserver INFO: Alarm Server Starting
Mar 31 21:52:00 alarmserver.EnvisalinkClient DEBUG: Staring Envisalink Client
Mar 31 21:52:00 alarmserver.EnvisalinkClient DEBUG: Connecting to 192.168.1.100:4025
Mar 31 21:52:00 alarmserver INFO: AlarmServer on HTTPS port 8111
Mar 31 21:52:00 alarmserver.EnvisalinkClient INFO: Connected to 192.168.1.100:4025
Mar 31 21:52:00 alarmserver.EnvisalinkClient DEBUG: RX < 505 - Login Interaction
Mar 31 21:52:00 alarmserver.EnvisalinkClient DEBUG: TX > 005[PASSWORD]D5
Mar 31 21:52:00 alarmserver.EnvisalinkClient DEBUG: RX < 500 - Command Acknowledge
Mar 31 21:52:00 alarmserver.EnvisalinkClient DEBUG: RX < 505 - Login Interaction
Mar 31 21:52:00 alarmserver.EnvisalinkClient DEBUG: TX > 00191
Mar 31 21:52:00 alarmserver.EnvisalinkClient ERROR: Disconnected from 192.168.1.100:4025
Mar 31 21:52:00 alarmserver.EnvisalinkClient WARNING: Connection failed, retrying in 10 seconds
Mar 31 21:52:10 alarmserver.EnvisalinkClient DEBUG: Connecting to 192.168.1.100:4025
Mar 31 21:52:10 alarmserver.EnvisalinkClient INFO: Connected to 192.168.1.100:4025
Mar 31 21:52:10 alarmserver.EnvisalinkClient ERROR: Disconnected from 192.168.1.100:4025
Mar 31 21:52:10 alarmserver.EnvisalinkClient WARNING: Connection failed, retrying in 10 seconds

**Comment by kholloway** [comment]
I had this issue when I first started and all I had to do was manually login one time via the TPI port using Telnet and then disconnect. After that the Python stuff started working properly as did anything else I tested.

**Comment by ekw** [comment]
I telnetted in, but still have the same problem.

**Comment by alexruffell** [comment]
I had a similar issue and it was due to more than one application trying to access Envisalink. Make sure the python script is the only thing accessing it. I deleted the device from my eyez-on account but I can't recall if that was necessary or just a troubleshooting step I did to get it working... either way I had no use for it.

**Comment by cchighman** [comment]
That's a pretty nasty bug, getting dropped like that.

2015-08-08 06:32:59 RX < 609 - Zone 028 Open
2015-08-08 06:32:59 RX < 510 - Keypad Led State - Partition 1
2015-08-08 06:32:59 RX < 651 - Partition Home Not Ready
2015-08-08 06:33:22 RX < 511 - Keypad Led Flash State - Partition 1
2015-08-08 06:33:22 Disconnected from 192.168.0.201:4025
2015-08-08 06:33:22 Connection failed, retrying in 10 seconds
2015-08-08 06:33:32 Connected to 192.168.0.201:4025
2015-08-08 06:33:32 RX < 511 - Keypad Led Flash State - Partition 1
2015-08-08 06:33:32 Disconnected from 192.168.0.201:4025
2015-08-08 06:33:32 Connection failed, retrying in 10 seconds
2015-08-08 06:33:42 Connected to 192.168.0.201:4025
2015-08-08 06:33:42 RX < 511 - Keypad Led Flash State - Partition 1
2015-08-08 06:33:42 Disconnected from 192.168.0.201:4025
2015-08-08 06:33:42 Connection failed, retrying in 10 seconds
2015-08-08 06:33:52 Connected to 192.168.0.201:4025
2015-08-08 06:33:52 RX < 511 - Keypad Led Flash State - Partition 1
2015-08-08 06:33:52 Disconnected from 192.168.0.201:4025
2015-08-08 06:33:52 Connection failed, retrying in 10 seconds

**Comment by carloss66** [comment]
I am experiencing the same bug.

**Comment by juggie** [comment]
@carloss66 @cchighman I haven't experienced this issue but I'll try forcefully kicking the envisalink off my network and confirm with the new code I've been working on that it is able to re-connect gracefully.

**Comment by juggie** [comment]
Btw, can you both try my new branch (feature/tornado) and see if it is still happening? That branch isn't 100% feature complete yet but the networking code is totally rewritten.

**Comment by cchighman** [comment]
I can try this.  I've had great luck with my AlarmServer having literally
months of uptime.  I'll compare.  How does one get involved with making
submissions to community branches?  We use Perforce at work but I haven't
ever submitted to an open source branch before.

**Comment by cchighman** [comment]
The error handling and sanity checks I had to add aren't present in the new version (implementation in Envisalink.py).  I found there were places where it was important to verify state before moving forward.  Particularly in handle_event.  My uptime is rediculous now and I have other devices accessing Envisalink, still able to maintain a persistent connection.

Attached below what I use (AlarmServer.py)

[alarmserver.txt](https://github.com/juggie/AlarmServer/files/139497/alarmserver.txt)

**Comment by juggie** [comment]
Hey @cchighman you would want to look into git (the source control used by github).  I don't know if you use windows, or linux, etc but instructions would differ slightly based on the platform.

In essence, you would take my code, fork it into your own github account.  Make your changes and then submit a pull request.

I took a look at the file you attached but it's against a old early 2014 version of master I think... I am not sure.. still looking for the exact commit you used so i can get a proper diff.

Could you elaborate on what you think is missing?  handle_event has been totally rewritten if you look at the code here: https://github.com/juggie/AlarmServer/blob/feature/tornado/core/envisalink.py#L173 It is much better and easier to follow.  It receives the event, does some checks and then uses events.put() to throw it to the event module.  That will bring it here: https://github.com/juggie/AlarmServer/blob/feature/tornado/core/events.py#L28 which will in turn hit the call back function here: https://github.com/juggie/AlarmServer/blob/feature/tornado/core/state.py#L25 which was registered earlier when state.py loaded.

Let me know what error handling and sanity checks you feel are missing.

**Comment by cchighman** [comment]
I found my previous comments to people on SmartThings forums.  I added a couple checks to make sure self._isloggedin == True.  I also recall adding try/catch in a couple other places such as handle_line or found_terminator in the older version.  Without running with the new version just yet, I just notice the same method is used in envisalink and doesn't check if logged in, which was tied to the unhandled exception below breaking the reconnect.

I believe the case was a device was logging into Envisalink and my TPI connection was dropped at the same time a handle_event was being processed.

> I'm sure this has been addressed but when AlarmServer.py is reconnecting after a disconnect event from TPI, it's possible the input it receives from Envisalink may be causing unhandled exceptions:
> 
> Exception
> 
> error: uncaptured python exception, closing channel <main.EnvisalinkClient connected 192.168.0.201:4025 at 0x102eeeb00> (:'type' [/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py|read|83] [/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py|handle_read_event|449] [/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asynchat.py|handle_read|158] [alarmserver.py|found_terminator|238] [alarmserver.py|handle_line|280] [alarmserver.py|handle_event|374] [alarmserver.py|callbackurl_event|388])
> Log
> 
> 2015-08-08 06:48:05 RX < 511 - Keypad Led Flash State - Partition 1
> 2015-08-08 06:48:05 Disconnected from 192.168.0.201:4025
> 2015-08-08 06:48:05 Connection failed, retrying in 10 seconds
> 2015-08-08 06:48:15 Connected to 192.168.0.201:4025
> I understand two things shouldn't attempt to access TPI port but in the event it does, it looks like some validation may be needed for this handle correctly, seems like a race condition.
> 
> Granted, I've had about 3 hours of experience total with this now trying to get SmartThings linked up to my DSC panel. Its hitting the callback URL and triggering the event so long as I don't connect to eyez-on to trigger some action.
> 
> I'll read back up through the thread after stepping through some of this code.

-----

> I added a condition in handle_event @ 340ish (beginning of def):
> 
>  if self._isloggedin == True:
> This way I don't attempt to handle an event and do some action if I'm not even logged in yet. Now, I'm reconnecting successfully for this case.
> 
> 2015-08-08 08:09:13 RX < 511 - Keypad Led Flash State - Partition 1
> 2015-08-08 08:09:13 Disconnected from 192.168.0.201:4025
> 2015-08-08 08:09:13 Connection failed, retrying in 10 seconds
> 2015-08-08 08:09:23 Connected to 192.168.0.201:4025
> 2015-08-08 08:09:23 RX < 511 - Keypad Led Flash State - Partition 1
> 2015-08-08 08:09:23 RX < 505 - Login Interaction
> 2015-08-08 08:09:23 TX > 005060305C3
> 2015-08-08 08:09:23 RX < 500 - Command Acknowledge
> 2015-08-08 08:09:23 RX < 505 - Login Interaction
> 2015-08-08 08:09:23 TX > 00191
> 2015-08-08 08:09:23 RX < 500 - Command Acknowledge
> 2015-08-08 08:09:23 RX < 609 - Zone A Open
> I'm using eyez-on to disarm/arm alarm and other TPI clients at the same time to force a disconnect by AlarmServer too.

**Comment by juggie** [comment]
@cchighman Ok great thanks, I'll take a look in the new code base, test, and make sure disconnections are handled properly.  self._isLoggedin isn't even used for anything to be honest, it could be removed.  handle_login is called when the login event is received, which is what envisalink sends when you connect.

**Comment by juggie** [comment]
@cchighman I played around with connect/disconnects this morning and made some improvements to the networking code.  There are no doubt still more places I might have to catch some exceptions to handle loss of the connection though as I only dealt with handle_connect() this morning.  Will need more testing, handle_line and send_command would be the two other functions I need to look at.

**Comment by juggie** [comment]
@cchighman I got the other two functions now and was able to force network failures without issue.  All network io operations now have exceptions wrapped around them however they just silence the errors.  In the case of tornado since there is a connection lost callback defined, that code automatically handles it so there is no special code required with the exception of handle_connect.
