### ISSUE TITLE
WIP: Tornado

### ISSUE THREAD

**Issue by juggie** [juggie/AlarmServer#33]
@kholloway @gschrader FYI, in the process of rewriting this on python-tornado.  See the branch if interested.

**Comment by juggie** [comment]
Mostly done, some loose ends.  I noticed a JS bug which is in the master code as well.  If a new event appears, the selected zone,tab will refresh to empty.  Clicking the zone/partition again loads the proper information.

**Comment by juggie** [comment]
@kholloway @gschrader Now that its based on tornado and i've rewritten the envisalink module to use a separate state module, I can easily add events over websocket (or any other kind of publisher, redis, amqp, etc).  I've have not re-enabled the envisalink proxy support yet and I am also going to add a extendable system of some sort for addons, be it for notifications, etc.  It should also be trivial to add support at this point for any other alarm systems.

**Comment by gschrader** [comment]
@juggie nice work, it would make sense to send the updates to the ui with websockets, I'm not sure when I'll have a chance to look at this though.

**Comment by juggie** [comment]
Yeah totally it would be trivial to add a websocket now.  Its on my to do
list.

**Comment by juggie** [comment]
BTW, plugins are done and can hang off 3 kinds of events (currently).

**Comment by juggie** [comment]
@gschrader Any thoughts on how to best apply some sort of intelligent event filtering configurable by each plugin?

I think the filter should be pushed up to the event code so each plugin doesn't need to implement it and only needs to register what they want.  However, i'd like to do it in a generic way that isn't specifically tied to envisalink codes or anything like that.  Maybe I need to update envisalinkdefs to include some sort of grouping on the event types.

**Comment by gschrader** [comment]
Does it matter if the plugins get every event and they can decide if they care about it or not?

**Comment by juggie** [comment]
Well, from a code standpoint it is certainly preferable to not have to write the same code in every plugin.

**Comment by juggie** [comment]
@gschrader Done, pushed filtering to events layer and now the plugin can chose which events it would like to filter which is done by the events layer before calling the plugin.  Currently supported is filtering of zone and partition events only on a zone or partition basis, eg zone 1 or partition 1.

**Comment by juggie** [comment]
Re-added proxy support, tested lightly.

**Comment by juggie** [comment]
Pushbullet support also added. (Joining pushover) As two supported push notification services.

**Comment by juggie** [comment]
Will merge this branch to master soon.
