### ISSUE TITLE
Shows incorrect time/date

### ISSUE THREAD

**Issue by juched78** [juggie/AlarmServer#34]
Playing with the new Tornado version and found that on startup my events were always "in 4 hours".  I am EST timezone.

I found that by changing the lines in state.py to:

                  'datetime' : str(datetime.datetime.now().strftime("%Y-%m-%dT%H:%M:%SZ")), 

By Adding a T inbetween and adding the Z on the end, this builds a proper ISO standard which indicates UTC timezone.  Now the web page automatically adjusts to my timezone and shows "few seconds ago", etc.

Fixed file attached.

[state.zip](https://github.com/juggie/AlarmServer/files/226885/state.zip)

**Comment by juggie** [comment]
Fixed.
