### ISSUE TITLE
Not loading conffile in new Tornado Version

### ISSUE THREAD

**Issue by juched78** [juggie/AlarmServer#35]
I found that the new Tornado version doesn't properly load the conffile.  I took from the old branch and simplified and added this code to the main function right after the set default config line:

    #set default config
    conffile='alarmserver.cfg'
	
    try:
        opts, args = getopt.getopt(argv, "c:", ["config="])
    except getopt.GetoptError:
        sys.exit(2)
    for opt, arg in opts:
        if opt in ("-c", "--config"):
            conffile = arg

Now it loads with the -c option when not in the same folder.

Attached fixed file.

[alarmserver.zip](https://github.com/juggie/AlarmServer/files/226887/alarmserver.zip)

**Comment by juggie** [comment]
Thanks for your fix.  You are right that when I did the rewrite I did not add the cli parameters for overriding the config!  Thanks for your fix.

Have you used git much?  While in this case your code change was very easy to integrate, sometimes things are not so simple.  If you forked a copy of my code into your own repo, you would be able to commit back to it and then open a pull request with your changes.  If you encounter anything else you'd like to fix feel free to ask me for more information.

**Comment by juched78** [comment]
I have not used git before.  I will learn and see how to do this so I can make it easier to submit.

thank you for creating this server.  Having fun using it.

**Comment by juggie** [comment]
It's no problem, take a look it does make things quite easy.  You will have to fork the code into your own github user, then you can use git to check the code out to your machine.  Make changes/commits, and when you are happy you can submit a pull request (which basically notifies me you have changes you wish to merge with my code).  It's very simple once you try it.  Let me know if you have any questions.
