### ISSUE TITLE
Logging in Tornado version doesn't write to file

### ISSUE THREAD

**Issue by juched78** [juggie/AlarmServer#36]
Noticed that after I setup this server on my router (running Tomato by Shibby) and running this as a service in the background I had no way to figure out why my pushover alerts were not working (turns out that was because I didn't have the updated CA certs so SSL filed, a quick opkg install ca-certificates fixed that).

So, I made some updates to the attached files to NOT use the logger class for config loading (that always uses print now to to go stdout) and moved the importing of classes to after the config is loaded so that all other classes can now write to the configured output file in the cfg file.

Use this if you like, I do think this tweak makes logging when running as a service usable.    Attached is the code diff.

Thank you.

[logtofilechanges.zip](https://github.com/juggie/AlarmServer/files/227049/logtofilechanges.zip)

**Comment by rct** [comment]
PR #48 has these changes so you don't have to deal with the .zip file.
