### ISSUE TITLE
Plugins do not load if current working directory is not the folder with alarmserver.py

### ISSUE THREAD

**Issue by juched78** [juggie/AlarmServer#37]
One more quick one.  If the current working directory is not the same as the folder with alarmserver.py, then the plugin code doesn't find the plugin folder and no plugins work.

This occurs when you run the python script as a service (using start-stop-daemon).  

The fix is to get the current directory of the alarmserver.py file (not the current working directory) and to build the search for plugins based on that.  Code is updated below:

    #load plugins - TODO: make this way better
    currpath = os.path.dirname(os.path.abspath(__file__))
    plugins = glob.glob(currpath+"/plugins/*.py")
    for p in plugins:
        if str.find(p, '__init__.py') != -1: continue
        name = p[p.rfind('/')+1:p.find('.')]
        exec "from plugins import %s" % name
        exec "%s.init()" % name

**Comment by juched78** [comment]
I will try to setup git tomorrow.

**Comment by juggie** [comment]
Thanks would be happy to have you contribute and git would make it easier!

**Comment by juggie** [comment]
Your code change was committed.
