### ISSUE TITLE
feature req/help: TZ configurable (tornado branch)

### ISSUE THREAD

**Issue by ikishk** [juggie/AlarmServer#40]
Timezone awareness?

So far I've done the following:
alarmserver.cfg, line 11:
logurlrequests=True

**## Timezone, UTC default
timezone="America/Chicago"**

config.py, line 18:
        config.LOGURLREQUESTS = ....
        **config.ASTZ = config.read_config_var('alarmserver', 'timezone', 'UTC', 'str')**
        config.HTTPSPORT = .....

state.py, line 1:
**#**import datetime
**from datetime import datetime
import pytz**
# alarmserver modules

import logger
from config import config
from events import events

**##config.ASTZ='America/Chicago'
utc_now = datetime.now()
if config.ASTZ != 'UTC':
  logger.debug('Timezone set to' + config.ASTZ)
  tz = pytz.timezone(config.ASTZ)
  now = tz.localize(utc_now)
else:
  now = utc_now**

class state():

running it like this gives me "AttributeError: class config has no attribute 'ASTZ'", uncommenting the ASTZ above works.

The API call shows the proper time using the timezone ("datetime": "2016-05-11T13:17:00Z"}), however the JS on the index page still shows UTC (Today at 8:17 AM).

So, 2 questions... 
1)why isn't it reading in the config file as expected?
2)why isnt the index html/js/ajax page showing the API time?

**Comment by rct** [comment]
On the current version of feature/tornado from Juggie's repo, All time stamps are "4 hours ago".   Setting eventtimeago to False didn't seem to fix this.  I don't know if that's implemented. yet.

If I had to make a guess where 4 hours is coming from it is my offset from GMT.

**Comment by juggie** [comment]
I will try to look at this weekend just moved been very busy.

**Comment by rct** [comment]
Currently in tornado last event times are somewhat broken.
1. It doesn't look like a Zone Timer dump is ever requested.
2. The Zone Timer Dump isn't processed, there is no handler for it.

**Comment by ikishk** [comment]
not to nag... any update on this? (kinda fell off my radar)

**Comment by juggie** [comment]
Events not set to be in UTC but string indicated it was UTC.  Let me know if this fixes the issue, no need to add timezone configuration.

**Comment by ikishk** [comment]
that fixed it, thank you!
