### ISSUE TITLE
Enabling TPI Time stamps breaks response parsing.

### ISSUE THREAD

**Issue by rct** [juggie/AlarmServer#43]
Tested with Tornado branch, probably somewhat expected:
Enabling TPI time stamps through the proxy breaks parsing, leaving alarm server in a broken state.

core/envisalink/handle_line generates a ValueError trying to parse 'HH:' with int().

If TPI timestamps are enabled, they stay enabled even after a disconnect/reconnect cycle. 

The response format when them enabled is 'HH:MM:SS 500....'

Send a '0550CA' to turn them back off.

**Comment by rct** [comment]
There should probably be a separate issue opened for Tornado where exceptions due to parsing problems leave alarmserver running but broken after a "Future Exception was never retrieved".

**Comment by juggie** [comment]
Hey @rct I've never used TPI time stamps, but it would certainly be trivial to add support for them.  The parsing of the response could be done much better w/ a REGEX.  What is the use case though, do you trust the time more on your TPI then your python machine?

**Comment by rct** [comment]
I don't have a specific use case for this at the moment.  I saw this in the TPI docs as something new and not backward compatible.  AlarmServer might not use it, but some software connected to the proxy could enable it and break AlarmServer.

**Comment by juggie** [comment]
@rct The only issue with the proxy and TPI is if one app were to request time stamps and one not.

**Comment by rct** [comment]
@juggie agreed, I think. 
* AlarmServer should be able to handle TPI codes with/without timestamps.  So if a proxy connected app turns it on/off it doesn't affect AlarmServer.
* There is a the problem if someone is using two apps through the proxy and one enables timestamps, it might break the other app. Which is probably fine. That's the way the API is at this point. If it becomes a problem and someone is sufficiently motivated they could make the proxy keep state on per-connection basis.

**Comment by rct** [comment]
With #49 on the tornado branch, it won't matter if TPI timestamps are enabled or not. Currently the raw line is being passed through to proxy clients, so the issue of handling them is pushed downstream for now.

Nothing is being done with the TPI timestamps at the moment. The clock in my EVL-4 drifts pretty badly, around a second every 4 minutes. It looks like the EVL resets itself to about a minute fast as soon as the EVL clock is far enough off for the minute to be different.
