### ISSUE TITLE
Handle Zone Bypass Status Message TPI Code 616.

### ISSUE THREAD

**Issue by rct** [juggie/AlarmServer#46]
Recently TPI response 616 -  Zone Bypass Status was added to the TPI.  See See http://forum.eyez-on.com/FORUM/viewtopic.php?f=6&t=301&start=80.  NOTE: Envisacor has released DSC TPI 1.07 on June 1st, 2016

> Bypassed Zones Bitfield Dump
This command is issued upon leaving Zone Bypass programming (*1 on the keypad). It is a 16 character HEX string representing an 8 byte bitfield. This bitfield indicates which zones are currently in bypass. A “1” indicates the zone is in bypass. The lower 8 zones are in the first position of the bitfield. The developer can force this dump by using the keystring commands to enter and leave zone bypassing. i.e. “*1#”

That description isn't terribly clear.  1st byte is zones 1-8 bitmap, 2nd byte is 9-16, 
```
00 00 00 00 00 00 00 00
00 00 62 06 00 00 00 00
|| || || || || || || ||
|| || || || || || || ||
|| || || || || || || 57-64
|| || || || || || ||
|| || || || || || 49-56
|| || || || || ||
|| || || || || 41-48
|| || || || ||
|| || || || 33-40
|| || || ||
|| || || 25-32
|| || ||
|| || 17-24
|| ||
|| 9-16
||
1-8
```

To trigger the Zone Bypass response for Partition 1 send `0711*1#` 

Note: this only works for partition 1.

**Comment by juggie** [comment]
Patched by @rct
