### ISSUE TITLE
Envisalink 4 compatibility

### ISSUE THREAD

**Issue by adrianmihalko** [juggie/AlarmServer#58]
I have DSC alarm and Envisalink 4 and I am trying to run your project.

All I got is an empty page at root and on /api
{"version": 0.3}

Do you have any idea how to get this work?
[output.log.txt](https://github.com/juggie/AlarmServer/files/945301/output.log.txt)

**Comment by rct** [comment]
I'm running an EVL-4 for 9+ months, so it's not a compatibility problem. 

Make sure logging is turned on and capture the log or stdout/stderr.

Can you provide some more info about your setup?

**Comment by rct** [comment]
I didn't see that you provided a log file.   This python exception shouldn't be there.   Not sure if it's a tornado version problem or related to your config.

```
Apr 20 21:47:21 - ERROR: Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/madrian/domoticz/userscripts/AlarmServer/core/envisalink.py", line 62, in do_connect
    self._connection = yield self.tcpclient.connect(config.ENVISALINKHOST, config.ENVISALINKPORT)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/tcpclient.py", line 176, in connect
    addrinfo = yield self.resolver.resolve(host, port, af)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 363, in submit
    future.set_result(fn(*args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/tornado/netutil.py", line 390, in resolve
    addrinfo = socket.getaddrinfo(host, port, family, socket.SOCK_STREAM)
gaierror: [Errno -2] Name or service not known
```

**Comment by kholloway** [comment]
That error indicates that Python can't resolve the hostname that you gave it for your envisalink device. Make sure the DNS name resolvers or try replacing it with the actual IP of the envisalink device.

**Comment by rct** [comment]
Looks like it might not be able to handle a dotted quad.
```
Apr 20 21:47:21 - DEBUG - core/envisalink.py:do_connect@60: Connecting to '192.168.1.251':4025
```

**Comment by kholloway** [comment]
Why are the single quotes there? Wonder if the config value is quoted in the file, if that's the case remove the quotes and try again.

**Comment by juggie** [comment]
Does your config have quotes in the host line?  If so remove them, it should be host=192..168.x.x

**Comment by adrianmihalko** [comment]
Ahh, for some reason I had IP address in quotes. Removing quotes resolved the problem. It works very nicely now.

One more question: is there any "bypass zone" or even better to enter custom sequence feature?

**Comment by adrianmihalko** [comment]
Guys, two more question:

-it is possible to change timezone from UTC? It showing me incorrect time, because I am in other timezone.
-I am thinking in Domoticz integration. I am looking for a simple way to call an url (domoticz's device change), when a zone is triggered. It is possible somehow? Other things can be done trough Alarmserver's API. 

-Oh yeah, I asked this before, it is possible to enter custom sequences (to bypass zones etc.)?

Any help greatly appreciated,
Adrian

**Comment by juggie** [comment]
The API is in UTC.  That's intentional.  Are you seeing UTC in the UI?  I see EDT (EST) correctly.  But the browser is doing the time  conversion in Javascript.

You can 100% write a Domoticz plugin.  Take a look at one of the existing plugins.  eg: https://github.com/juggie/AlarmServer/blob/master/plugins/pushbullet.py

I'm not sure what you mean by your final question.  It would totally be possible to expose a interface to send custom commands, but that does not exist at this time.

**Comment by juggie** [comment]
BTW, if you have further things, open a new issue.  This one has been fixed.
