### ISSUE TITLE
Improve envisalink host not found handling. 

### ISSUE THREAD

**Issue by rct** [juggie/AlarmServer#59]
Close this issue when a failure resolving the envisalink's host name is handled better.  It should be clear to the user from the logs and the UI that the problem is 'host not found'.

It should be also be clear to the user and the API that alarmserver isn't connected to the envisalink / is unable to connect. 

When this came up in issue #58, it was due to a configuration file problem.

There are two ways this condition could be handled.  Both have some merit

1. Treat 'hot not found' as a fatal error, log appropriate messages and exit.
2. Treat this as possibly a transient error, (DNS failure?), and retry indefinitely.

In any case, the behavior to be avoided is having alarmserver keep running, while not connected and not attempting to retry.

**Comment by juggie** [comment]
Needs better exception handling for sure.  If the host name can't be resolved, we should bail and exit.  There is already code to reconnect as I recall, would have to look.
