### ISSUE TITLE
Could not get any response - 

### ISSUE THREAD

**Issue by Parkash067** [juggie/AlarmServer#63]
I am using Jessie OS on raspberrypi3 and also created SSL certificated using given command which is mention in the readme file but when I hit request http://192.168.0.xxx:8111/api  I didn't get any response on CLI I got these logs 

SSL Error on 12 ('192.168.0.xxx', 33810): [SSL: HTTP_REQUEST] http request (_ssl.c:581)

**Comment by rct** [comment]
Were you using a browser or something like curl?

Note: the certificate you generated won't be signed by a known certificate authority so it will generate a warning that must be bypassed in the browser.

**Comment by Parkash067** [comment]
Thanks for replying but this issue has resolved
