### ISSUE TITLE
Issue with Pushover alerts.

### ISSUE THREAD

**Issue by SirMaple** [juggie/AlarmServer#77]
I have pushover enabled in my alarmserver.cfg and I also have the following:

`## Define the event codes you want callbacks for, the codes below`
`## cover zone open/close, partition ready, not ready, armed, exit delay, entry delay and in alarm status`
`## these should cover most use cases`
`event_codes=601,602,700,701,750,751`

But why on earth do it get flooded with alerts when a zone opens and closes?

I didn't define that code for callbacks but yet I still get them.

Am I missing something in my setup? What else should I check?

**Comment by adrianmihalko** [comment]
I am not using this project anymore, but I suggest you to switch to Home Assistant which has 100% and good working support for Envisalink. With Home Assitant you can do anything you want.

**Comment by SirMaple** [comment]
I figured a way around this issue.

I simply send certain message received to my LibreNMS server using system and setup alerts there.

I added the following to my rsyslog.conf:
`if $msg contains '601' then @@192.168.0.145
`if $msg contains '602' then @@192.168.0.145
`if $msg contains '700' then @@192.168.0.145
`if $msg contains '701' then @@192.168.0.145
`if $msg contains '750' then @@192.168.0.145
`if $msg contains '751' then @@192.168.0.145
`& ~
