### ISSUE TITLE
Add some form of authentication

### ISSUE THREAD

**Issue by juggie** [juggie/AlarmServer#9]

**Comment by juggie** [comment]
Done, basic auth w/ single username and password.  Password stored in config as sha1.  Needs example in example config.

**Comment by juggie** [comment]
It will also default to no auth if one or both of username or password isn't set

**Comment by gerstl** [comment]
Except that it pops up an authentication dialog in the browser even if authentication is disabled (no password or username set in alarmserver.cfg). 

To fix, the check for auth_header in httpslistener_auth.py should be moved to after the the check for the config vars, see attached diff.

[alarmserver_diff.txt](https://github.com/juggie/AlarmServer/files/429140/alarmserver_diff.txt)

**Comment by juggie** [comment]
This is done, and bug above was fixed.
